name: Replace index.js in index.html

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  replace-index-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install cheerio
        run: npm install cheerio

      - name: Replace index.js in index.html
        run: |
          # Write the modified HTML content to build.html file
          echo "wow" > build.html

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-website
          path: build.html

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-website
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts
